schema_version = "1.0.0"
id = "leaf_gen"
version = "1.0.3"
name = "Leaf Gen"
tagline = "An add-on to create leaf retopology and procedural leaf shading"
maintainer = "Guillaume Bissieres"
type = "add-on"
website = "https://bissieres.gumroad.com/l/LeafGen"
tracker_url = "https://github.com/GuillaumeBissieres/blender-leaf-gen/issues"
tags = ["Mesh"]
blender_version_min = "4.2.0"
license = [
"SPDX:GPL-3.0-or-later",
]
